## Numpy Basics

In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]
type(mylist)

list

In [6]:
newlist = np.array(mylist)
newlist
# type(newlist)

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat
type(my_mat)

list

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# Creating a range
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
# Create a 1D array of zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
# Using linspace - gives you n list of numbers linearly spaced between the start and stop, 
# where n is the last parameter
np.linspace(0,30,11)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [18]:
# An identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

In [23]:
# Creating random distribution of data
np.random.rand(2,4)

array([[0.03913658, 0.6524792 , 0.89357251, 0.5242182 ],
       [0.96341463, 0.15658769, 0.14580169, 0.74202051]])

In [25]:
# Using a standard normal distribution
np.random.randn(10)
np.random.randn(2,3)

array([[-0.3512536 , -0.35353867,  0.53334628],
       [ 1.31488799, -2.13181222,  0.46642832]])

In [32]:
# For random integers, the last parameter indicates the number of integers you want
np.random.randint(2,101,6)
np.random.randint(1,200,(3,4))

array([[179,  96,  66, 175],
       [135,  82, 120,  98],
       [156, 193,  63, 117]])

In [41]:
# The seed is used to set a random state,
# so that the random results can actually be reproduced.
# NB: The seed should be in the same cell as the random number exprpession
np.random.seed(42)
np.random.randint(1,4,5)

array([3, 1, 3, 3, 1])

---

In [48]:
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
intrandy = np.random.randint(0,101,5)
intrandy

array([20, 82, 86, 74, 74])

In [50]:
intrandy.min()

20

In [51]:
intrandy.max()

86

In [52]:
intrandy.argmin()

0

In [53]:
intrandy.argmax()

2