In [27]:
import numpy as np
my_list = [[1,2,3],[1,2,4],[3,4,5]]
my_list2 = [[1,2,1],[1,2,6],[3,1,5]]
a = np.array(my_list)
a
# print(a.dtype)
# print(np.ndim(a))
print(np.shape(a))
# type(a)
newwy = my_list + my_list2
print(newwy)
print(np.dot(my_list,my_list2))

(3, 3)
[[1, 2, 3], [1, 2, 4], [3, 4, 5], [1, 2, 1], [1, 2, 6], [3, 1, 5]]
[[12  9 28]
 [15 10 33]
 [22 19 52]]


In [19]:
x = np.array([1,2,3,4])
xe = np.zeros_like(x)
xe

array([0, 0, 0, 0])

In [25]:
xi = np.identity(4)
xeye = np.eye(4)
# xi
xeye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])